[build]
  command = "npm install && npm run build"
  publish = "build"
  functions = "functions-build"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200